### ISSUE TITLE
ACCOUNTING

### ISSUE THREAD

**Issue by PYDIPALA-SAI-AKASH** [PYDIPALA-SAI-AKASH/vasavirep#1]
modify the code

**Comment by mohanbangaru** [comment]
done

**Comment by Abhirambeella008** [comment]
I was modify the accounting files test party.py price (list) to price (packages)...work done

**Comment by mohanreddypadala** [comment]
replaced full with half
![Uploading Screenshot 2023-11-15 113316.png…]()

**Comment by mohanbangaru** [comment]
replaced half with full
![Screenshot 2023-09-27 121622](https://github.com/PYDIPALA-SAI-AKASH/vasavirep/assets/150769786/d1328c49-b08f-4e44-b5f4-60ed8f0cb428)

**Comment by mohanbangaru** [comment]
replace half with full
![Screenshot (358)](https://github.com/PYDIPALA-SAI-AKASH/vasavirep/assets/150769786/0a195765-4837-4eb0-9bdd-8c10112713b0)
